# Generated by Django 4.1.7 on 2023-04-10 01:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import djrichtextfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=500)),
                ('supplies', djrichtextfield.models.RichTextField(max_length=10000)),
                ('pattern_guide', djrichtextfield.models.RichTextField(max_length=10000)),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[400, None], upload_to='patterns/')),
                ('image_alt', models.CharField(max_length=100)),
                ('pattern_type', models.CharField(choices=[('crossstitch', 'CrossStitch'), ('blackwork', 'Blackwork'), ('embroidery', 'Embroidery')], default='mixed', max_length=50)),
                ('colors', models.IntegerField()),
                ('date_posted', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pattern_creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_posted'],
            },
        ),
    ]
